# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Modrot < Formula
  desc "Detect archived/deprecated dependencies and inactive projects in go.mod files"
  homepage "https://github.com/norman-abramovitz/modrot"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/norman-abramovitz/modrot/releases/download/v0.2.0/modrot_0.2.0_darwin_amd64.tar.gz"
      sha256 "a5fac789fe04aeba5aaee05e4ddc051ea0721742e813881d3c0960c72d1dcf12"

      def install
        bin.install "modrot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/norman-abramovitz/modrot/releases/download/v0.2.0/modrot_0.2.0_darwin_arm64.tar.gz"
      sha256 "f179615cbba736e5dcc9d2961291fd82bc11fc291fb6d81f2d42c9012727a00a"

      def install
        bin.install "modrot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/norman-abramovitz/modrot/releases/download/v0.2.0/modrot_0.2.0_linux_amd64.tar.gz"
      sha256 "6079927f1cc7e9bdce4f19edd805c6524ee63c2332fd133b38a187d106dfb703"
      def install
        bin.install "modrot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/norman-abramovitz/modrot/releases/download/v0.2.0/modrot_0.2.0_linux_arm64.tar.gz"
      sha256 "adad6b9a4fd1e1f01d6b75ed962d2b3e0453704f78c01c8cf718cef28124a5e5"
      def install
        bin.install "modrot"
      end
    end
  end
end
