# This file was generated by GoReleaser. DO NOT EDIT.
cask "modrot" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "6e6ca786dfc5440c2a4c4aad40541861b147a7ea2f1a895d5451e269a2aa41cd"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1a6ad1011aa0a511c829979db4aeae7cf374a46acd02c0c6fd01d3a31198483"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa99b1e5609207b5e882f3f1e7c6951fd26ee898dab86f99b1c773009ea80722"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fefd83fc1401a312b7864a79a24ed6a9b4594c6986143a0b2c7185eca2281bf1"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "modrot"
  desc "Detect archived/deprecated dependencies and inactive projects in go.mod files"
  homepage "https://github.com/norman-abramovitz/modrot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modrot"

  # No zap stanza required

end
