# This file was generated by GoReleaser. DO NOT EDIT.
cask "modrot" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_darwin_amd64.tar.gz"
      sha256 "275b1102ac91dec3432cf39bdc85a2b0e980ea3e15884692c2116797b3dfd744"
    end
    on_arm do
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_darwin_arm64.tar.gz"
      sha256 "2bf3d39292b202ba94fda69e96aea6a8f9f845363740f22cf19a05830f6d2b86"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_linux_amd64.tar.gz"
      sha256 "6cd7cd9e63093830b5aef5f3c85fec8f0c59bebabfaa524bd0d4f167eea2a425"
    end
    on_arm do
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_linux_arm64.tar.gz"
      sha256 "06f87c747e12fdf52425d5fb79c610cd2c3df07fc405fbd7dd411bd2322b3e2b"
    end
  end

  name "modrot"
  desc "Detect archived/deprecated dependencies and inactive projects in go.mod files"
  homepage "https://github.com/norman-abramovitz/modrot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modrot"

  # No zap stanza required

end
