# This file was generated by GoReleaser. DO NOT EDIT.
cask "modrot" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "041b8a128ebd703d9056daf283d17e660710fe975ee90795787ab0ac2b432a0e"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a417499556ad1eedd849ccb26a17bcfc3d0608ccf4cdf261ac01ea844ac4c2f"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "02d9e65ca97845f1fbf40927e218e8af1979e01d82c7b99ea91e32ba3ecc41f3"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac472d124de4cba2e5924b5b4b96fea21785ef38e51a4e446f4ab2f412927ea2"
      url "https://github.com/norman-abramovitz/modrot/releases/download/v#{version}/modrot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "modrot"
  desc "Detect archived/deprecated dependencies and inactive projects in go.mod files"
  homepage "https://github.com/norman-abramovitz/modrot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modrot"

  # No zap stanza required

end
